language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/schnaeppchenfuchs_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/schnaeppchenfuchs_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: CODECOV=1 DEFAULT=0

before_install:
  - sh -c "if [ '$CODECOV' = '1' ]; then sudo pip install codecov; fi"

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"
  - sh -c "if [ '$CODECOV' = '1' ]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi"

after_success:
  - sh -c "if [ '$CODECOV' = '1' ]; then codecov; fi"

notifications:
  email: false
